import localFont from "next/font/local";
import "./globals.css";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>KŽ pedagogė</title>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <header class="header">
        <div class="logo">
        <a href="/"><img src="https://i.ibb.co/7SyPNTN/marguerite.png" alt="logo" /></a>
        <a href="/"><h2>KŽ</h2></a>
        </div>
        <nav class="navbar">
        <ul class="navlinks">
          <li><a href="/">Pagrindinis</a></li>
          <li><a href="/Apiemane">Apie mane</a></li>
          <li><a href="/Paslaugos">Paslaugos</a></li>
          <li><a href="/Kainos">Kainos</a></li>
          <li><a href="/Kontaktai">Kontaktai</a></li>
        </ul>
        </nav>
        <div class="hamburger">
            <div class="bar"></div>
            <div class="bar"></div>
            <div class="bar"></div>
        </div>
      </header>
      {children}
      <footer class="footer">
            <p>@ 2024 Karolina Žemčūžnikovienė</p>
            <a href="/"><img src="https://i.ibb.co/7SyPNTN/marguerite.png" alt="instalogo" /></a>
        </footer>
      </body>
      
    </html>
  );
  
}




